name: click_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  supabase_flutter: ^2.12.0
  uuid: ^4.5.3
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
